import { useState } from "react";

const SAMPLE_TREATMENTS = [
  {
    patientId: "P001",
    firstName: "John",
    lastName: "Kamwendo",
    drug: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    status: "available",
    numberOfTablets: 2,
    duration: "6 months",
    totalTablets: 360,
    dateIssued: "2024-01-01",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    patientId: "P002",
    firstName: "Mary",
    lastName: "Phiri",
    drug: "Insulin",
    dosage: "10 units",
    frequency: "Before meals",
    status: "available",
    numberOfTablets: 3,
    duration: "3 months",
    totalTablets: 270,
    dateIssued: "2024-02-15",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    patientId: "P003",
    firstName: "Blessings",
    lastName: "Mwanza",
    drug: "Glibenclamide",
    dosage: "5mg",
    frequency: "Once daily",
    status: "out of stock",
    numberOfTablets: 1,
    duration: "1 month",
    totalTablets: 30,
    dateIssued: "2023-11-01",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    patientId: "P004",
    firstName: "James",
    lastName: "Chirwa",
    drug: "Amlodipine",
    dosage: "5mg",
    frequency: "Once daily",
    status: "available",
    numberOfTablets: 1,
    duration: "1 month",
    totalTablets: 30,
    dateIssued: "2024-03-10",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    patientId: "P005",
    firstName: "Esther",
    lastName: "Banda",
    drug: "Vildagliptin",
    dosage: "50mg",
    frequency: "Twice daily",
    status: "available",
    numberOfTablets: 2,
    duration: "2 months",
    totalTablets: 120,
    dateIssued: "2024-04-05",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    patientId: "P006",
    firstName: "Henry",
    lastName: "Kachingwe",
    drug: "Gliclazide",
    dosage: "80mg",
    frequency: "Twice daily",
    status: "out of stock",
    numberOfTablets: 2,
    duration: "4 months",
    totalTablets: 240,
    dateIssued: "2024-03-20",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    patientId: "P007",
    firstName: "Grace",
    lastName: "Phiri",
    drug: "Sitagliptin",
    dosage: "100mg",
    frequency: "Once daily",
    status: "available",
    numberOfTablets: 1,
    duration: "3 months",
    totalTablets: 90,
    dateIssued: "2024-02-28",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    patientId: "P008",
    firstName: "Peter",
    lastName: "Mwale",
    drug: "Metformin ER",
    dosage: "1000mg",
    frequency: "Once daily",
    status: "available",
    numberOfTablets: 1,
    duration: "6 months",
    totalTablets: 180,
    dateIssued: "2024-01-15",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    patientId: "P009",
    firstName: "Sarah",
    lastName: "Banda",
    drug: "Pioglitazone",
    dosage: "15mg",
    frequency: "Once daily",
    status: "available",
    numberOfTablets: 1,
    duration: "2 months",
    totalTablets: 60,
    dateIssued: "2024-04-12",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    patientId: "P010",
    firstName: "Michael",
    lastName: "Tembo",
    drug: "Dapagliflozin",
    dosage: "10mg",
    frequency: "Once daily",
    status: "out of stock",
    numberOfTablets: 1,
    duration: "1 month",
    totalTablets: 30,
    dateIssued: "2024-04-18",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
  },
];

export const useDosage = () => {
  const [treatments, setTreatments] = useState(SAMPLE_TREATMENTS);

  const handleEdit = (item) => {
    console.log("Editing treatment:", item);
  };

  return {
    treatments,
    handleEdit,
  };
};
